after_script:
  - docker images

before_script:
  - IMAGE="bitcoin-abc:${VERSION/\//-}"

env:
  - VERSION=0.21.1

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Bitcoin ABC"

services: docker
